{{- if .Values.prometheusRules.istio.optimization.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: istio-metrics-optimization
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-prometheus
    name: prometheus
spec:
  groups:
  - name: "istio.recording-rules"
    interval: {{ .Values.prometheusRules.istio.optimization.interval }}
    rules:
    - record: "istio:istio_requests:by_destination_service:rate1m"
      expr: |
        sum(irate(istio_requests_total{reporter="destination"}[1m]))
        by (
          destination_canonical_service,
          destination_workload_namespace
        )
    - record: "istio:istio_request_duration_milliseconds_bucket:p95:rate1m"
      expr: |
        histogram_quantile(0.95,
          sum(irate(istio_request_duration_milliseconds_bucket{reporter="source"}[1m]))
          by (
            destination_canonical_service,
            destination_workload_namespace,
            source_canonical_service,
            source_workload_namespace,
            le
          )
        )
{{- end }}
