apiVersion: v1
appVersion: v1.8.3
description: Provide easy log collecting definition for kubernetes pods and their
  hosts, and management of fluentbit
icon: https://dashboard.snapcraft.io/site_media/appmedia/2020/02/logo-square.png
keywords:
- fluentbit
- custom resouces
maintainers:
- name: TACO Team
- email: usnexp@gmail.com
  name: sungil
name: fluentbit-resource
sources:
- https://github.com/intelliguy/fluentbit-operator
version: 1.3.1
# Support Multi-ElasticSeach clusters (1.0.0)
# Support loki (1.1.0)
# Support Custom Parser with Parser CR (1.1.0)
