apiVersion: {{ .Values.api.group.infrastructure }}/{{ .Values.api.version }}
kind: AWSCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  region: {{ .Values.cluster.region }}
  sshKeyName: {{ .Values.sshKeyName }}
  {{- with .Values.cluster.networkSpec }}
  networkSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  bastion:
    enabled: {{ .Values.cluster.bastion.enabled }}
    {{- if .Values.cluster.bastion.enabled  }}
    instanceType: {{ .Values.cluster.bastion.instanceType }}
    disableIngressRules: {{ .Values.cluster.bastion.disableIngressRules }}
    {{- with .Values.cluster.bastion.allowedCIDRBlocks }}
    allowedCIDRBlocks:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- if .Values.cluster.baseOS }}
  imageLookupBaseOS: {{ .Values.cluster.baseOS }}
  {{- end }}
