{{- if .Values.cluster.eksEnabled }}
apiVersion: {{ .Values.api.group.controlplane }}/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  eksClusterName: {{ .Values.cluster.name }}
  region: {{ .Values.cluster.region }}
  sshKeyName: {{ .Values.sshKeyName }}
  version: {{ .Values.cluster.kubernetesVersion }}
  addons:
    {{- toYaml .Values.cluster.eksAddons | nindent 4 }}
  bastion:
    enabled: {{ .Values.cluster.bastion.enabled }}
    {{- if .Values.cluster.bastion.enabled  }}
    instanceType: {{ .Values.cluster.bastion.instanceType }}
    disableIngressRules: {{ .Values.cluster.bastion.disableIngressRules }}
    {{- with .Values.cluster.bastion.allowedCIDRBlocks }}
    allowedCIDRBlocks:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
{{- end }}
