{{- if .Values.kubeadmControlPlane.enabled }}
apiVersion: {{ .Values.api.group.infrastructure }}/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: {{ .Values.kubeadmControlPlane.controlPlaneMachineType }}
      sshKeyName: {{ .Values.sshKeyName }}
      rootVolume:
        size: {{ .Values.kubeadmControlPlane.rootVolume.size }}
        type: {{ .Values.kubeadmControlPlane.rootVolume.type }}
      {{- if .Values.kubeadmControlPlane.ami }}
      ami:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
