apiVersion: {{ .Values.api.group.cluster }}/{{ .Values.api.version }}
kind: Cluster
metadata:
  labels:
    ccm: external
    csi: external
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: {{ .Values.cluster.podCidrBlocks }}
  infrastructureRef:
    apiVersion: {{ .Values.api.group.infrastructure }}/v1beta2
    {{- if .Values.cluster.eksEnabled }}
    kind: AWSManagedCluster
    {{- else }}
    kind: AWSCluster
    {{- end }}
    name: {{ .Values.cluster.name }}
  controlPlaneRef:
    {{- if .Values.cluster.eksEnabled }}
    apiVersion: {{ .Values.api.group.controlplane }}/v1beta2
    kind: AWSManagedControlPlane
    {{- else }}
    apiVersion: {{ .Values.api.group.controlplane }}/{{ .Values.api.version }}
    kind: KubeadmControlPlane
    {{- end }}
    name: {{ .Values.cluster.name }}
