apiVersion: {{ .Values.api.group.cluster }}/{{ .Values.api.version }}
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.machinePool }}
  clusterNetwork:
    pods:
      cidrBlocks: {{ .Values.cluster.podCidrBlocks }}
  {{- end }}
  infrastructureRef:
    {{- if .Values.cluster.eksEnabled }}
    apiVersion: {{ .Values.api.group.controlplane }}/{{ .Values.api.version }}
    kind: AWSManagedControlPlane
    name: "{{ .Values.cluster.name }}-eks-control-plane"
    {{- else }}
    apiVersion: {{ .Values.api.group.infrastructure }}/{{ .Values.api.version }}
    kind: AWSCluster
    name: {{ .Values.cluster.name }}
    {{- end }}
  controlPlaneRef:
    apiVersion: {{ .Values.api.group.controlplane }}/{{ .Values.api.version }}
    {{- if .Values.cluster.eksEnabled }}
    kind: AWSManagedControlPlane
    name: "{{ .Values.cluster.name }}-eks-control-plane"
    {{- else }}
    kind: KubeadmControlPlane
    name: "{{ .Values.cluster.name }}-control-plane"
    {{- end }}
