{{- if not .Values.cluster.eksEnabled }}
kind: KubeadmControlPlane
apiVersion: {{ .Values.api.group.controlplane }}/{{ .Values.api.version }}
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.kubeadmControlPlane.replicas }}
  machineTemplate:
    infrastructureRef:
      apiVersion: {{ .Values.api.group.infrastructure }}/v1beta2
      kind: AWSMachineTemplate
      name: "{{ .Values.cluster.name }}-control-plane"
  rolloutBefore:
    certificatesExpiryDays: 21 # trigger a rollout if certificates expire within 21 days
  kubeadmConfigSpec:
    {{- with .Values.kubeadmControlPlane.clusterConfiguration }}
    clusterConfiguration:
      {{- with .apiServer }}
      apiServer:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .controllerManager }}
      controllerManager:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .etcd }}
      etcd:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    initConfiguration:
      nodeRegistration:
        name: '{{`{{ ds.meta_data.local_hostname }}`}}'
        kubeletExtraArgs:
          cloud-provider: aws
    joinConfiguration:
      nodeRegistration:
        name: '{{`{{ ds.meta_data.local_hostname }}`}}'
        kubeletExtraArgs:
          cloud-provider: aws
  version: {{ .Values.cluster.kubernetesVersion }}
---
apiVersion: {{ .Values.api.group.infrastructure }}/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: {{ .Values.kubeadmControlPlane.controlPlaneMachineType }}
      sshKeyName: {{ .Values.sshKeyName }}
      rootVolume:
        size: {{ .Values.kubeadmControlPlane.rootVolume.size }}
        type: {{ .Values.kubeadmControlPlane.rootVolume.type }}
      {{- if .Values.kubeadmControlPlane.ami }}
      ami:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeadmControlPlane.additionalSecurityGroups }}
      additionalSecurityGroups:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
