{{- $envAll := . }}
{{- range .Values.machinePool }}
---
apiVersion: {{ $envAll.Values.api.group.cluster }}/{{ $envAll.Values.api.version }}
kind: MachinePool
metadata:
  name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
  namespace: {{ $envAll.Release.Namespace }}
{{- if $envAll.Values.cluster.eksEnabled }}
  annotations:
    cluster.x-k8s.io/replicas-managed-by: "external-autoscaler"
{{- end }}
spec:
  clusterName: {{ $envAll.Values.cluster.name }}
  replicas: {{ .replicas }}
  template:
    metadata:
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 12 }}
      {{- end }}
    spec:
      bootstrap:
        {{- if $envAll.Values.cluster.eksEnabled }}
        dataSecretName: ""
        {{- else }}
        configRef:
          apiVersion: {{ $envAll.Values.api.group.bootstrap }}/{{ $envAll.Values.api.version }}
          kind: KubeadmConfig
          name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
          namespace: {{ $envAll.Release.Namespace }}
        {{- end }}
      clusterName: {{ $envAll.Values.cluster.name }}
      infrastructureRef:
        apiVersion: {{ $envAll.Values.api.group.infrastructure }}/v1beta2
        {{- if $envAll.Values.cluster.eksEnabled }}
        kind: AWSManagedMachinePool
        {{- else }}
        kind: AWSMachinePool
        {{- end }}
        name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
        namespace: {{ $envAll.Release.Namespace }}
      version: {{ $envAll.Values.cluster.kubernetesVersion }}
---
apiVersion: {{ $envAll.Values.api.group.infrastructure }}/v1beta2
{{- if $envAll.Values.cluster.eksEnabled }}
kind: AWSManagedMachinePool
metadata:
  name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
  namespace: {{ $envAll.Release.Namespace }}
spec:
  eksNodegroupName: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
  instanceType: {{ .machineType }}
  diskSize: {{ .rootVolume.size }}
  scaling:
    maxSize: {{ .maxSize }}
    minSize: {{ .minSize }}
  remoteAccess:
    sshKeyName: {{ $envAll.Values.sshKeyName }}
{{- else }}
kind: AWSMachinePool
metadata:
  name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
  namespace: {{ $envAll.Release.Namespace }}
spec:
  awsLaunchTemplate:
    instanceType: {{ .machineType }}
    sshKeyName: {{ $envAll.Values.sshKeyName }}
    iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
    rootVolume:
      size: {{ .rootVolume.size }}
      type: {{ .rootVolume.type }}
    {{- if .ami }}
    ami:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  maxSize: {{ .maxSize }}
  minSize: {{ .minSize }}
  subnets:
  - filters:
    - name: "tag:sigs.k8s.io/cluster-api-provider-aws/role"
      values:
      - "private"
    - name: "tag:Name"
      values:
      - "*{{ $envAll.Values.cluster.name }}*"
---
apiVersion: {{ $envAll.Values.api.group.bootstrap }}/{{ $envAll.Values.api.version }}
kind: KubeadmConfig
metadata:
  name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
  namespace: {{ $envAll.Release.Namespace }}
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: aws
      name: '{{`{{ ds.meta_data.local_hostname }}`}}'
{{- end }}
{{- end }}
