{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-aws.serviceAccountName" . }}
  labels:
    {{- include "cluster-api-aws.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cluster-api-aws.fullname" . }}
rules:
- apiGroups:
  - 'infrastructure.cluster.x-k8s.io'
  resources:
  - awsclusters
  verbs: 
  - get
  - list
  - watch
- apiGroups:
  - 'exp.cluster.x-k8s.io'
  resources:
  - machinepools
  verbs:
  - get
  - list
  - create
- apiGroups:
  - 'infrastructure.cluster.x-k8s.io'
  resources:
  - awsmachinepools
  verbs:
  - get
  - list
  - create
- apiGroups:
  - 'bootstrap.cluster.x-k8s.io'
  resources:
  - kubeadmconfigs
  verbs:
  - get
  - list
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  verbs: 
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - serviceaccount
  verbs: 
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cluster-api-aws.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cluster-api-aws.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-api-aws.serviceAccountName" . }}
{{- end }}
