{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-aws.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api-aws.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cluster-api-aws.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - 'infrastructure.cluster.x-k8s.io'
  resources:
  - awsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 'controlplane.cluster.x-k8s.io'
  resources:
  - awsmanagedcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 'exp.cluster.x-k8s.io'
  - 'cluster.x-k8s.io'
  resources:
  - machinepools
  verbs:
  - get
  - list
  - create
  - patch
  - delete
- apiGroups:
  - 'infrastructure.cluster.x-k8s.io'
  resources:
  - awsmachinepools
  verbs:
  - get
  - list
  - create
  - patch
  - delete
- apiGroups:
  - 'bootstrap.cluster.x-k8s.io'
  resources:
  - kubeadmconfigs
  verbs:
  - get
  - list
  - create
  - patch
  - delete
- apiGroups:
  - 'cluster.x-k8s.io'
  resources:
  - machinedeployments
  verbs:
  - get
  - list
  - create
  - patch
- apiGroups:
  - 'infrastructure.cluster.x-k8s.io'
  resources:
  - awsmachinetemplates
  verbs:
  - get
  - list
  - create
  - patch
- apiGroups:
  - 'bootstrap.cluster.x-k8s.io'
  resources:
  - kubeadmconfigtemplates
  verbs:
  - get
  - list
  - create
  - patch
- apiGroups:
  - 'bootstrap.cluster.x-k8s.io'
  resources:
  - eksconfigtemplates
  verbs:
  - get
  - list
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs: 
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - serviceaccount
  verbs: 
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cluster-api-aws.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cluster-api-aws.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-api-aws.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api-aws.fullname" . }}
rules:
- apiGroups:
  - 'apiextensions.k8s.io'
  resources:
  - customresourcedefinitions
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-api-aws.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-api-aws.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-api-aws.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
