{{- if and .Values.fluentbit.enabled }}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  name: fluent-bit-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.4.5
spec:
  service:
    parsersFile: parsers.conf
    logLevel: warning
{{- if podMonitor.enabled }}
    httpListen: 0.0.0.0
    httpPort: 2020
    httpServer: true
{{- end }}
  inputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
  filterSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"      
  outputSelector:
    matchLabels:
      fluentbit.fluent.io/enabled: "true"
{{- end}}