{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.workflow.enabled }}
---
apiVersion: {{ printf "%s/v1" (.Values.prometheus.crdApiGroup | default "monitoring.coreos.com") }}
kind: ServiceMonitor
metadata:
  name: argo-workflows-server
  namespace: lma
  labels:
    release: prometheus-operator
spec:
  jobLabel: argo-workflows-server
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows-server
  endpoints:
  - port: http
    {{- if .Values.serviceMonitor.workflow.interval }}
    interval: {{ .Values.serviceMonitor.workflow.interval }}
    {{- end }}
    path: "/metrics"
{{- if .Values.serviceMonitor.workflow.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.workflow.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.serviceMonitor.workflow.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.workflow.relabelings | indent 6 }}
{{- end }}
---
apiVersion: {{ printf "%s/v1" (.Values.prometheus.crdApiGroup | default "monitoring.coreos.com") }}
kind: ServiceMonitor
metadata:
  name: argo-workflows-controller
  namespace: lma
  labels:
    release: prometheus-operator
spec:
  jobLabel: argo-workflows-controller
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows-workflow-controller
  endpoints:
  - port: metrics
    {{- if .Values.serviceMonitor.workflow.interval }}
    interval: {{ .Values.serviceMonitor.workflow.interval }}
    {{- end }}
    path: "/metrics"
{{- if .Values.serviceMonitor.workflow.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.workflow.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.serviceMonitor.workflow.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.workflow.relabelings | indent 6 }}
{{- end }}

{{- end }}
