{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.calico.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    k8s-app: calico-node
  name: calico-exporter
  namespace: kube-system
spec:
  ports:
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    k8s-app: calico-node
  sessionAffinity: None
  type: ClusterIP
{{- end}}