annotations:
  category: Analytics
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.8.2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: kube-state-metrics is a simple service that listens to the Kubernetes
  API server and generates metrics about the state of the objects.
home: https://github.com/bitnami/charts/tree/main/bitnami/kube-state-metrics
icon: https://bitnami.com/assets/stacks/kube-state-metrics/img/kube-state-metrics-stack-220x234.png
keywords:
- prometheus
- kube-state-metrics
- monitoring
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: kube-state-metrics
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/kube-state-metrics
- https://github.com/kubernetes/kube-state-metrics
version: 3.3.4
