apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa-scorecard.fullname" . }}
  labels:
    {{- include "opa-scorecard.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "opa-scorecard.selectorLabels" . | nindent 4 }}
