apiVersion: v2
name: cluster-api-openstack
description: Install Cluster API Provider OpenStack manifests to generate a fully working Kubernetes cluster 
keywords:
- clusterapi 
- provisioning
- bootstrapping 
- kubernetes
type: application
version: 1.0.0
appVersion: 0.0.1
maintainers:
- name: Jugwan Eom
  email: zugwan@gmail.com

dependencies:
- name: helm-toolkit
  version: ">= 0.1.0"
  repository: https://openinfradev.github.io/helm-repo
  # from https://opendev.org/openstack/openstack-helm-infra/src/branch/master/helm-toolkit
