{
 "title": "[TKS] Kubernetes / Nodes",
 "description": "This is a Node dashboard for your Kubernetes cluster(s). Made for prometheus and take advantage of the latest Grafana features.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "taco_cluster", "label": "Cluster", "query": { "query": "label_values(up, taco_cluster)" } },
   {
    "name": "hostname",
    "label": "Host Name",
    "query": {
     "query": "label_values(node_uname_info{taco_cluster=~\"$taco_cluster\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System logs：【$hostname】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Trend for log collection",
   "type": "timeseries",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\",host=~\"$hostname\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "logs (/Identifier)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\",host=~\"$hostname\"}[$__interval])) by (ident)"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"syslog\",host=~\"$hostname\"}"
    }
   ]
  },
  { "title": "Resource Details：【$hostname】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=~\"$hostname\"} / (node_memory_MemTotal_bytes{hostname=~\"$hostname\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{hostname=~\"$hostname\"} + 1)/ (node_memory_SwapTotal_bytes{hostname=~\"$hostname\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 17 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{hostname=~\"$hostname\", mode='system'})"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{hostname=~\"$hostname\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{hostname=~\"$hostname\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total filefd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "【$taco_cluster】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\",hostname=~\"$hostname\"}-0",
     "legendFormat": "Quantity"
    },
    {
     "expr": "node_filesystem_avail_bytes {taco_cluster=~\"$taco_cluster\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\",hostname=~\"$hostname\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\",hostname=~\"$hostname\"}-node_filesystem_free_bytes{taco_cluster=~\"$taco_cluster\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\",hostname=~\"$hostname\"}) *100/(node_filesystem_avail_bytes {taco_cluster=~\"$taco_cluster\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\",hostname=~\"$hostname\"}+(node_filesystem_size_bytes{taco_cluster=~\"$taco_cluster\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\",hostname=~\"$hostname\"}-node_filesystem_free_bytes{taco_cluster=~\"$taco_cluster\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\",hostname=~\"$hostname\"}))"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{hostname=~\"$hostname\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{hostname=~\"$hostname\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{hostname=~\"$hostname\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"system\"}[5m])) by (hostname) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"user\"}[5m])) by (hostname) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"iowait\"}[5m])) by (hostname) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{hostname=~\"$hostname\",mode=\"idle\"}[5m])) by (hostname))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{hostname=~\"$hostname\"} - node_memory_MemAvailable_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=~\"$hostname\"} / (node_memory_MemTotal_bytes{hostname=~\"$hostname\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{hostname=~'$hostname',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "Time read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{hostname=~\"$hostname\"}[5m]) / irate(node_disk_reads_completed_total{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{hostname=~\"$hostname\"}[5m]) / irate(node_disk_writes_completed_total{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{device}}_Write time"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{hostname=~\"$hostname\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "irate(node_context_switches_total{hostname=~\"$hostname\"}[5m])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Network (Bandwidth)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bps", "label": "RX（-）/ TX（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{hostname=~'$hostname',device=~\"eth.*|enp.*|ens.*\"}[5m])*8",
     "legendFormat": "TX"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{hostname=~'$hostname', device=~\"eth.*|enp.*|ens.*\"}[5m])*8*-1",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Network (PPS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "bps", "label": "RX（-）/ TX（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{hostname=~'$hostname',device=~\"eth.*|enp.*|ens.*\"}[5m])",
     "legendFormat": "TX"
    },
    {
     "expr": "irate(node_network_receive_packets_total{hostname=~'$hostname',device=~\"eth.*|enp.*|ens.*\"}[5m]) * -1",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Network (drops)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "# drops" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{hostname=~\"$hostname\", device=~\"eth.*|enp.*|ens.*\"}[5m])",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Resource All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Resource Overview",
     "type": "table-old",
     "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "node_uname_info{taco_cluster=~\"$taco_cluster\"} - 0",
       "legendFormat": "Host Name"
      },
      {
       "expr": "sum(time() - node_boot_time_seconds{taco_cluster=~\"$taco_cluster\"})by(hostname)",
       "legendFormat": "Uptime"
      },
      {
       "expr": "node_memory_MemTotal_bytes{taco_cluster=~\"$taco_cluster\"} - 0",
       "legendFormat": "Memory"
      },
      {
       "expr": "count(node_cpu_seconds_total{mode='system',taco_cluster=~\"$taco_cluster\"}) by (hostname)",
       "legendFormat": "CPU Cores"
      },
      {
       "expr": "node_load5{taco_cluster=~\"$taco_cluster\"}",
       "legendFormat": "5m Load"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",taco_cluster=~\"$taco_cluster\"}[5m])) by (hostname)) * 100",
       "legendFormat": "CPU Used"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{taco_cluster=~\"$taco_cluster\"} / (node_memory_MemTotal_bytes{taco_cluster=~\"$taco_cluster\"})))* 100",
       "legendFormat": "Memory Used"
      },
      {
       "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"})))by(hostname)",
       "legendFormat": "Partition Used"
      },
      {
       "expr": "max(irate(node_disk_read_bytes_total{taco_cluster=~\"$taco_cluster\"}[5m])) by (hostname)",
       "legendFormat": "Disk Read"
      },
      {
       "expr": "max(irate(node_disk_written_bytes_total{taco_cluster=~\"$taco_cluster\"}[5m])) by (hostname)",
       "legendFormat": "Disk Write"
      },
      {
       "expr": "max(irate(node_network_receive_bytes_total{taco_cluster=~\"$taco_cluster\"}[5m])*8) by (hostname)",
       "legendFormat": "Download"
      },
      {
       "expr": "max(irate(node_network_transmit_bytes_total{taco_cluster=~\"$taco_cluster\"}[5m])*8) by (hostname)",
       "legendFormat": "Upload"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", taco_cluster=~\"$taco_cluster\"}[5m])) by (hostname)) * 100 + on(hostname) group_left(nodename) \nnode_uname_info{taco_cluster=~\"$taco_cluster\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Mem Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{ taco_cluster=~\"$taco_cluster\"} / (node_memory_MemTotal_bytes{ taco_cluster=~\"$taco_cluster\"})))* 100 + on(hostname) group_left(nodename) \nnode_uname_info{taco_cluster=~\"$taco_cluster\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",taco_cluster=~\"$taco_cluster\"})))by(hostname) + on(hostname) group_left(nodename) \nnode_uname_info{taco_cluster=~\"$taco_cluster\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Network Usage (TX)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by (hostname) (irate(node_network_transmit_bytes_total{device=~\"eth.*|enp.*|ens.*\", taco_cluster=~\"$taco_cluster\"}[5m])) * 8 + on(hostname) group_left(nodename) \nnode_uname_info{taco_cluster=~\"$taco_cluster\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Network Usage (RX)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by (hostname) (irate(node_network_receive_bytes_total{device=~\"eth.*|enp.*|ens.*\", taco_cluster=~\"$taco_cluster\"}[5m])) * 8 + on(hostname) group_left(nodename) \nnode_uname_info{taco_cluster=~\"$taco_cluster\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}