{
 "title": "[TKS] Kubernetes / View / Pods (v1)",
 "description": "This is a POD dashboard for your Kubernetes cluster(s). Made for prometheus and take advantage of the latest Grafana features. Orginated from GitHub repository.",
 "tags": [
  "Kubernetes",
  "tks",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "taco_cluster", "label": "taco_cluster", "query": { "query": "label_values(up, taco_cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{taco_cluster=~\"$taco_cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "전체 Cluster POD 현황 ($taco_cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Running POD Count (전체 Cluster)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{taco_cluster=~\"$taco_cluster\", created_by_kind != \"Workflow\"})"
    }
   ]
  },
  {
   "title": "Deployment Count (전체 Cluster)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Statefuleset Count (전체 Cluster)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(rate(container_cpu_usage_seconds_total{taco_cluster=~\"$taco_cluster\", image!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "Unavailable pods (전체 클러스터)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{taco_cluster=\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Daemonset Count (전체 Cluster)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_ready{taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{taco_cluster=~\"$taco_cluster\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "Pod Status (전체 Cluster)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{taco_cluster=~\"$taco_cluster\"}) by(pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pod Restart (전체 Cluster)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{taco_cluster=~\"$taco_cluster\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Namespace별 POD Dashboard (Namespace: $namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "POD Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Deployment 현황 (Namespace: $namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Deployment Count ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas{namespace=~\"$namespace\", taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Deployment Status ($namespace)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "current: {{ deployment }}"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace=~\"$namespace\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "available: {{ deployment }}"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "unavailable: {{ deployment }}"
    },
    {
     "expr": "kube_deployment_spec_replicas{namespace=~\"$namespace\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "deseired: {{ deployment }}"
    }
   ]
  },
  {
   "title": "Desired pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{taco_cluster=\"$taco_cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Desired pods per deployment",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{taco_cluster=\"$taco_cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Current pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{taco_cluster=\"$taco_cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Current pods per deployment",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{taco_cluster=\"$taco_cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Available pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{taco_cluster=\"$taco_cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Available pods per deployment",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{taco_cluster=\"$taco_cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{taco_cluster=\"$taco_cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Unavailable pods per deployment",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{taco_cluster=\"$taco_cluster\", namespace=~\"$namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "List of Deployment (Namespace: $namespace)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"$namespace\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Statefulset 현황 (Namespace: $namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }
  },
  {
   "title": "Statefuleset Count ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\", taco_cluster=~\"$taco_cluster\"})"
    }
   ]
  },
  {
   "title": "Statefuleset Status ($namespace)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas{namespace=~\"$namespace\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "desired: {{ statefulset }}"
    },
    {
     "expr": "kube_statefulset_status_replicas_current{namespace=~\"$namespace\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "current: {{ statefulset }}"
    },
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\", taco_cluster=\"$taco_cluster\"}",
     "legendFormat": "ready: {{ statefulset }}"
    }
   ]
  },
  {
   "title": "POD Resource (Namespace: $namespace / Pod: $pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "CPU ($container)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\",image!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU (POD)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(rate(container_cpu_usage_seconds_total{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\",pod=~\"$pod\",image!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage (Container: $container)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{taco_cluster=~\"$taco_cluster\", pod=~\"$pod\", container=~\"$container\", namespace=\"$namespace\", image!=\"\", container!=\"POD\"}[2m])",
     "legendFormat": "Current: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{taco_cluster=~\"$taco_cluster\", pod=~\"$pod\", container=~\"$container\", namespace=\"$namespace\",container!=\"POD\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{taco_cluster=~\"$taco_cluster\", pod=~\"$pod\", container=~\"$container\", namespace=\"$namespace\",container!=\"POD\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory ($container)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory (POD)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Usage (Container: $container)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(container) (container_memory_working_set_bytes{taco_cluster=~\"$taco_cluster\", pod=~\"$pod\", container=~\"$container\", namespace=\"$namespace\",container!=\"POD\",container!=\"\",image!=\"\"})",
     "legendFormat": "Current: {{ container  }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{taco_cluster=~\"$taco_cluster\", pod=~\"$pod\", container=~\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{taco_cluster=~\"$taco_cluster\", pod=~\"$pod\", container=~\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network TX Total (POD)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network RX Total (POD)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{taco_cluster=~\"$taco_cluster\", namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) "
    }
   ]
  },
  {
   "title": "POD Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate (container_network_transmit_bytes_total{taco_cluster=~\"$taco_cluster\", namespace=\"$namespace\", pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate (container_network_receive_bytes_total{taco_cluster=~\"$taco_cluster\", namespace=\"$namespace\", pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  }
 ]
}