{
 "title": "[TKS] Kubernetes Event Dashboard",
 "description": "event dashboard for kubernetes events on TACO using https://grafana.com/grafana/dashboards/12611-logging-universal-dashboard/",
 "tags": [
  "Loki",
  "event"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "level_type",
    "label": "Level",
    "query": "label_values({cluster=~\"$cluster\", type=~\".+\"}, type)"
   },
   {
    "name": "reason",
    "label": "Reason",
    "query": "label_values({cluster=~\"$cluster\", type=\"$level_type\"}, reason)"
   },
   {
    "name": "metadata_namespace",
    "label": "Namespace",
    "query": "label_values({cluster=~\"$cluster\", type=\"$level_type\"}, metadata_namespace)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of events",
   "type": "stat",
   "description": "Total  Count of events in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$level_type\", metadata_namespace=~\"$metadata_namespace\", reason=~\"$reason\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$level_type\", metadata_namespace=~\"$metadata_namespace\", reason=~\"$reason\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live events",
   "type": "logs",
   "description": "Live events is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{type=\"$level_type\", reason=~\"$reason\", metadata_namespace=~\"$metadata_namespace\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "events (/Namespace)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$level_type\", reason=~\"$reason\"})[$__interval])) by (metadata_namespace)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" (/Reason)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$level_type\", reason=~\"$reason\", metadata_namespace=~\"$metadata_namespace\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (reason)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$level_type\", metadata_namespace=~\"$metadata_namespace\", reason=~\"$reason\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({type=\"$level_type\", metadata_namespace=~\"$metadata_namespace\", reason=~\"$reason\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" COUNT (/Reason)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$level_type\", reason=~\"$reason\", metadata_namespace=~\"$metadata_namespace\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (reason)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate (/Reason)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({type=\"$level_type\", metadata_namespace=~\"$metadata_namespace\", reason=~\"$reason\"} |~ \"(?i)$searchable_pattern\")[30s])) by (reason)"
    }
   ]
  },
  {
   "title": "Count of events historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({type=\"$level_type\", reason=~\"$reason\"})[$__interval])) by (metadata_namespace)"
    }
   ]
  }
 ]
}