apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "prepare-etcd-secret.fullname" . }}
spec:
  template:
    metadata:
      name: {{ include "prepare-etcd-secret.fullname" . }}
    spec:
      serviceAccountName: {{ include "prepare-etcd-secret.serviceAccountName" . }}
      containers:
      - name: hyperkube
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        - |
          kubectl create secret generic etcd-client-cert \
          --namespace {{ .Release.Namespace }} \
      {{- if eq .Values.deployer "tks" }}
          --from-file=etcd-ca=/ssl/{{ .Values.etcd.certfile }} \
          --from-file=etcd-client=/ssl/{{ .Values.etcd.client_certfile }} \
          --from-file=etcd-client-key=/ssl/{{ .Values.etcd.client_keyfile }}
          --dry-run=client \
          -o yaml |  kubectl apply -f -
      {{- else if eq .Values.deployer "tacoplay" }}
          --from-file=etcd-ca=/ssl/{{ .Values.etcd.tacoplay_certfile }} \
          --from-file=etcd-client=/ssl/member-${MY_NODE_NAME}.pem \
          --from-file=etcd-client-key=/ssl/member-${MY_NODE_NAME}-key.pem \
          --dry-run=client \
          -o yaml |  kubectl apply -f -

        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      {{- else }}
          --wrong-value-for-deployer
      {{- end }}
        volumeMounts:
        - name: ssldir
          mountPath: /ssl
      volumes:
      - name: ssldir
        hostPath:
        {{- if eq .Values.deployer "tks" }}
          path: {{ .Values.etcd.certdir }}
        {{- else if eq .Values.deployer "tacoplay" }}
          path: {{ .Values.etcd.tacoplay_certdir }}
        {{- else }}
          wrong-value-for-deployer: recheck
        {{- end }}
          type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      restartPolicy: OnFailure
