{{- if and .Values.fluentbit.enabled }}
{{- $envAll := . }}

apiVersion: logging.kubesphere.io/v1alpha2
kind: Filter
metadata:
  name: kubernetes
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "kube.*"
  filters:
  - kubernetes:
      kubeURL: https://kubernetes.default.svc.{{.Values.global.base_cluster_url }}:443
      mergeLog: true
      labels: false
      annotations: false
  - nest:
      operation: lift
      nestedUnder: kubernetes
      addPrefix: kubernetes_
  - modify:
      rules:
      - remove: stream
      - remove: kubernetes_pod_id
      - remove: kubernetes_docker_id
      - remove: kubernetes_container_hash
  - nest:
      operation: nest
      wildcard:
      - kubernetes_*
      nestUnder: kubernetes
      removePrefix: kubernetes_
  - rewriteTag:
      rules:
{{- range .Values.fluentbit.exclude }}
      - {{ printf "%v ^(%v)$ intended_drop.$TAG false" .key .value }}
{{- end }}
{{- range .Values.fluentbit.targetLogs }}
  {{- range .multi_index }}
      - {{ printf "%v ^(%v)$ seperate.%v.$TAG false" .key .value .index }}
  {{- end}}
{{- end}}
{{- range .Values.fluentbit.alerts.rules }}
      - {{ printf "$log (%v) m_%v.$TAG true" .regex .severity }}
{{- end }}
      emitterName: alertrule_match
---
{{- range .Values.fluentbit.targetLogs }}
  {{- tuple $envAll . | include "fluentbit-operator.fluentbit.filter.throttle" }}
  {{- range .multi_index }}
    {{- tuple $envAll . | include "fluentbit-operator.fluentbit.filter.throttle" }}
  {{- end}}
{{- end}}
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Filter
metadata:
  name: simplify
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "m_*"
  filters:
  - nest:
      operation: lift
      nestedUnder: kubernetes
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Filter
metadata:
  name: add-info
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "kube*"
  filters:
  - modify:
      rules:
      - add:
          cluster: {{.Values.fluentbit.clusterName }}
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Filter
metadata:
  name: add-hostname
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "kubenode.*"
  filters:
  - modify:
      rules:
      - add:
          hostname: ${HOSTNAME}
{{- range .Values.fluentbit.alerts.rules }}
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Filter
metadata:
  name: add-{{.severity}}
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "m_{{.severity}}.*"
  filters:
  - modify:
      rules:
      - add:
          level: {{.severity}}
{{- end}}
{{- end}}
