{{- if .Values.fluentbit.enabled }}
{{- $envAll := . }}

{{ range .Values.fluentbit.outputs.es }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluentbit-operator.operator.es-secret" .name }}
  namespace: {{ $envAll.Release.Namespace }}
type: Opaque
data:
  username: {{ .username | b64enc }}
  password: {{ .password | b64enc }}

  {{- $es := . -}}
  {{- range $i, $input := $envAll.Values.fluentbit.targetLogs }}
    {{- $log := . -}}
    {{- if and (not $input.do_not_store_as_default) (eq .es_name $es.name) }}
---
    {{- tuple  $envAll $es .type $input.name $input.tag | include "fluentbit-operator.fluentbit.output.es" }}
    {{- end }}
    {{ range $input.multi_index }}
      {{- if  eq .es_name $es.name  }}
---
      {{- $newTag := (printf "seperate.%s.*" .index) }}
    # all, es, type, name, tag, index
      {{- tuple  $envAll $es $log.type .index $newTag .index | include "fluentbit-operator.fluentbit.output.es" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if and $envAll.Values.fluentbit.outputs.http.enabled }}
---
# regex-based log exporter
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: {{ template "fluentbit-operator.fullname" $envAll }}-exporter
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "m_*"
  http:
    host: {{ template "fluentbit-operator.name" $envAll  }}-exporter.{{ $envAll.Release.Namespace }}.svc.{{ $envAll.Values.global.base_cluster_url }}
    port: 2112
    uri: "/logs"
    format: json
{{- end }}
{{- if $envAll.Values.fluentbit.outputs.kafka.enabled }}
---
# kafka support
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: {{ template "fluentbit-operator.fullname" $envAll  }}-kafka
  namespace: {{ $.Release.Namespace }}
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "kube*"
  kafka:
    brokers: {{ $envAll.Values.fluentbit.outputs.kafka.broker }}
    topics: {{ $envAll.Values.fluentbit.outputs.kafka.topic }}
    format: json
{{- end }}
{{- end }}
